spring.application.name=airBnbApp

#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/airBnb
spring.datasource.username=postgres
spring.datasource.password=force123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true

server.servlet.context-path=/api/v1

#JWT Configuration
jwt.secretKey=lkar3452345245flbfsglfsdgjsdfl_3223dsdsldlkjvdkksfdljvfdssssssf344343

frontend.url=http://localhost:8080

